prophet_model:
  model_name: "prophet_model"
  sensor_name: "station_1"
  model_params:
    days_ahed: 14
    sps :  10.0
    cps :  0.25
    sm  : 'additive'
    ws  : 'auto'
    plot_range : False
    plot_pred_test : False